"""
Timeline Builder & Report Generator
"""

from typing import List, Dict, Any
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus.flowables import Flowable
from io import BytesIO
import math


# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
BRAND_DARK   = colors.HexColor('#0F172A')   # navy
BRAND_ACCENT = colors.HexColor('#3B82F6')   # blue
BRAND_LIGHT  = colors.HexColor('#EFF6FF')   # pale blue
GREY_100     = colors.HexColor('#F8FAFC')
GREY_200     = colors.HexColor('#E2E8F0')
GREY_500     = colors.HexColor('#64748B')
GREY_700     = colors.HexColor('#334155')
WHITE        = colors.white

TACTIC_COLORS = {
    'Initial Access':        ('#FEF3C7', '#D97706'),
    'Execution':             ('#FEE2E2', '#DC2626'),
    'Persistence':           ('#FEF9C3', '#CA8A04'),
    'Privilege Escalation':  ('#FFF7ED', '#EA580C'),
    'Defense Evasion':       ('#F3E8FF', '#9333EA'),
    'Credential Access':     ('#FFE4E6', '#E11D48'),
    'Discovery':             ('#E0F2FE', '#0284C7'),
    'Lateral Movement':      ('#ECFDF5', '#059669'),
    'Collection':            ('#F0FDF4', '#16A34A'),
    'Exfiltration':          ('#FDF2F8', '#DB2777'),
    'Command and Control':   ('#FFFBEB', '#B45309'),
    'Impact':                ('#FFF1F2', '#BE123C'),
}

SEVERITY_MAP = {
    'Initial Access': 'HIGH',
    'Execution': 'CRITICAL',
    'Persistence': 'HIGH',
    'Privilege Escalation': 'CRITICAL',
    'Defense Evasion': 'HIGH',
    'Credential Access': 'CRITICAL',
    'Discovery': 'MEDIUM',
    'Lateral Movement': 'HIGH',
    'Collection': 'MEDIUM',
    'Exfiltration': 'CRITICAL',
    'Command and Control': 'HIGH',
    'Impact': 'CRITICAL',
}

SEVERITY_COLORS = {
    'CRITICAL': ('#FEE2E2', '#DC2626'),
    'HIGH':     ('#FFF7ED', '#C2410C'),
    'MEDIUM':   ('#FEF9C3', '#A16207'),
    'LOW':      ('#F0FDF4', '#15803D'),
}

TACTICS_ORDER = [
    'Initial Access', 'Execution', 'Persistence', 'Privilege Escalation',
    'Defense Evasion', 'Credential Access', 'Discovery', 'Lateral Movement',
    'Collection', 'Exfiltration', 'Command and Control', 'Impact'
]


# ---------------------------------------------------------------------------
# Custom Flowable: coloured badge
# ---------------------------------------------------------------------------
class Badge(Flowable):
    def __init__(self, text, bg_hex, fg_hex, width=70, height=14):
        Flowable.__init__(self)
        self.text   = text
        self.bg     = colors.HexColor(bg_hex)
        self.fg     = colors.HexColor(fg_hex)
        self.width  = width
        self.height = height

    def draw(self):
        self.canv.setFillColor(self.bg)
        self.canv.roundRect(0, 0, self.width, self.height, 3, fill=1, stroke=0)
        self.canv.setFillColor(self.fg)
        self.canv.setFont('Helvetica-Bold', 7)
        self.canv.drawCentredString(self.width / 2, 3, self.text)


# ---------------------------------------------------------------------------
# Page template: header & footer on every page
# ---------------------------------------------------------------------------
def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Top bar
    canvas.setFillColor(BRAND_DARK)
    canvas.rect(0, h - 28, w, 28, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont('Helvetica-Bold', 9)
    canvas.drawString(18, h - 18, 'MITRE ATT&CK INCIDENT REPORT')
    canvas.setFont('Helvetica', 8)
    canvas.drawRightString(w - 18, h - 18, f'CONFIDENTIAL  |  Page {doc.page}')

    # Bottom bar
    canvas.setFillColor(GREY_200)
    canvas.rect(0, 0, w, 20, fill=1, stroke=0)
    canvas.setFillColor(GREY_500)
    canvas.setFont('Helvetica', 7)
    canvas.drawString(18, 6, 'Generated by MITRE Incident Mapper  •  Powered by MITRE ATT&CK® Framework')
    canvas.drawRightString(w - 18, 6, datetime.now().strftime('%Y-%m-%d %H:%M UTC'))

    canvas.restoreState()


# ---------------------------------------------------------------------------
# TimelineBuilder
# ---------------------------------------------------------------------------
class TimelineBuilder:
    def build_timeline(self, events: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        sorted_events = sorted(events, key=lambda x: x.get('timestamp', ''))
        timeline_phases: Dict[str, list] = {}
        for event in sorted_events:
            tactic = event.get('mitre_tactic', 'Unknown')
            timeline_phases.setdefault(tactic, []).append(event)
        return [
            {'tactic': t, 'events': timeline_phases[t]}
            for t in TACTICS_ORDER if t in timeline_phases
        ]


# ---------------------------------------------------------------------------
# ReportGenerator
# ---------------------------------------------------------------------------
class ReportGenerator:

    # ------------------------------------------------------------------ styles
    def _make_styles(self):
        base = getSampleStyleSheet()
        return {
            'cover_title': ParagraphStyle(
                'CoverTitle', parent=base['Normal'],
                fontSize=30, fontName='Helvetica-Bold',
                textColor=WHITE, alignment=TA_LEFT, leading=34,
            ),
            'cover_sub': ParagraphStyle(
                'CoverSub', parent=base['Normal'],
                fontSize=11, fontName='Helvetica',
                textColor=colors.HexColor('#94A3B8'), alignment=TA_LEFT,
            ),
            'section_title': ParagraphStyle(
                'SectionTitle', parent=base['Normal'],
                fontSize=13, fontName='Helvetica-Bold',
                textColor=BRAND_DARK, spaceBefore=14, spaceAfter=6,
            ),
            'label': ParagraphStyle(
                'Label', parent=base['Normal'],
                fontSize=8, fontName='Helvetica-Bold',
                textColor=GREY_500, spaceAfter=2,
            ),
            'value': ParagraphStyle(
                'Value', parent=base['Normal'],
                fontSize=10, fontName='Helvetica-Bold',
                textColor=BRAND_DARK, spaceAfter=0,
            ),
            'body': ParagraphStyle(
                'Body', parent=base['Normal'],
                fontSize=9, fontName='Helvetica',
                textColor=GREY_700, leading=13, spaceAfter=4,
            ),
            'small': ParagraphStyle(
                'Small', parent=base['Normal'],
                fontSize=8, fontName='Helvetica',
                textColor=GREY_700, leading=11,
            ),
            'table_header': ParagraphStyle(
                'TH', parent=base['Normal'],
                fontSize=8, fontName='Helvetica-Bold',
                textColor=WHITE,
            ),
            'table_cell': ParagraphStyle(
                'TD', parent=base['Normal'],
                fontSize=8, fontName='Helvetica',
                textColor=GREY_700, leading=11,
            ),
            'tactic_label': ParagraphStyle(
                'TacticLabel', parent=base['Normal'],
                fontSize=8, fontName='Helvetica-Bold',
                textColor=BRAND_DARK,
            ),
        }

    # ------------------------------------------------------------------ helpers
    def _rule(self, color=GREY_200, thickness=0.5):
        return HRFlowable(width='100%', thickness=thickness, color=color, spaceAfter=6, spaceBefore=4)

    def _stat_box(self, label, value, bg, fg):
        """Single stat card as a 1-cell table."""
        bg_c = colors.HexColor(bg)
        fg_c = colors.HexColor(fg)
        tbl = Table([[
            Paragraph(f'<font color="{fg}" size="18"><b>{value}</b></font>', ParagraphStyle(
                '_sv', fontSize=18, fontName='Helvetica-Bold',
                textColor=fg_c, alignment=TA_CENTER)),
        ], [
            Paragraph(f'<font color="#64748B" size="7">{label}</font>', ParagraphStyle(
                '_sl', fontSize=7, fontName='Helvetica',
                textColor=GREY_500, alignment=TA_CENTER)),
        ]], colWidths=[1.4 * inch])
        tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), bg_c),
            ('ROUNDEDCORNERS', [4, 4, 4, 4]),
            ('TOPPADDING',    (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING',   (0, 0), (-1, -1), 6),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 6),
            ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
            ('BOX',           (0, 0), (-1, -1), 0.5, colors.HexColor(fg)),
        ]))
        return tbl

    # ------------------------------------------------------------------ cover
    def _cover_page(self, story, incident, styles):
        w, h = A4
        incident_id = incident.get('incident_id', 'N/A')
        created_at  = incident.get('created_at', datetime.now().isoformat())[:19].replace('T', ' ')
        filename    = incident.get('filename', 'Unknown')
        events      = incident.get('events', [])
        techniques  = incident.get('mitre_techniques', [])

        # Dark cover banner
        banner = Table([['']], colWidths=[w - 2 * inch], rowHeights=[2.4 * inch])
        banner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BRAND_DARK),
            ('ROUNDEDCORNERS', [6, 6, 6, 6]),
        ]))
        story.append(Spacer(1, 0.15 * inch))
        story.append(banner)

        # Overlay text (drawn after, using absolute positioning via a table trick)
        cover_text = Table([
            [Paragraph('INCIDENT REPORT', styles['cover_title'])],
            [Paragraph('MITRE ATT&CK® Threat Intelligence Analysis', styles['cover_sub'])],
            [Spacer(1, 0.1 * inch)],
            [Paragraph(f'<font color="#3B82F6"><b>{incident_id}</b></font>',
                       ParagraphStyle('cid', fontSize=13, fontName='Helvetica-Bold',
                                      textColor=BRAND_ACCENT))],
        ], colWidths=[w - 2.6 * inch])
        cover_text.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BRAND_DARK),
            ('TOPPADDING',    (0, 0), (-1, -1), 18),
            ('LEFTPADDING',   (0, 0), (-1, -1), 20),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 18),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 20),
            ('ROUNDEDCORNERS', [6, 6, 6, 6]),
        ]))
        # Replace the blank banner with actual text banner
        story.pop()
        story.append(cover_text)
        story.append(Spacer(1, 0.25 * inch))

        # Stat cards row
        total_events = len(events)
        tactic_set   = set(e.get('mitre_tactic', '') for e in events)
        critical_count = sum(1 for e in events if SEVERITY_MAP.get(e.get('mitre_tactic', ''), 'LOW') == 'CRITICAL')
        avg_conf = (sum(e.get('confidence', 0) for e in events) // max(total_events, 1))

        stat_row = Table([[
            self._stat_box('TOTAL EVENTS',      str(total_events),    '#EFF6FF', '#2563EB'),
            self._stat_box('TECHNIQUES',         str(len(techniques)), '#FFF7ED', '#C2410C'),
            self._stat_box('TACTICS COVERED',   str(len(tactic_set)), '#F0FDF4', '#15803D'),
            self._stat_box('CRITICAL EVENTS',   str(critical_count),  '#FEF2F2', '#DC2626'),
            self._stat_box('AVG CONFIDENCE',    f'{avg_conf}%',       '#FAF5FF', '#7C3AED'),
        ]], colWidths=[1.45 * inch] * 5)
        stat_row.setStyle(TableStyle([
            ('ALIGN',  (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING',  (0, 0), (-1, -1), 3),
            ('RIGHTPADDING', (0, 0), (-1, -1), 3),
        ]))
        story.append(stat_row)
        story.append(Spacer(1, 0.2 * inch))
        story.append(self._rule(GREY_200))

        # Meta info grid
        meta_data = [
            ['INCIDENT ID', incident_id,   'GENERATED AT', created_at],
            ['SOURCE FILE', filename,       'TOTAL EVENTS', str(total_events)],
        ]
        meta_tbl = Table(meta_data, colWidths=[1.0 * inch, 2.8 * inch, 1.0 * inch, 2.4 * inch])
        meta_tbl.setStyle(TableStyle([
            ('FONTNAME',  (0, 0), (-1, -1), 'Helvetica'),
            ('FONTNAME',  (0, 0), (0, -1),  'Helvetica-Bold'),
            ('FONTNAME',  (2, 0), (2, -1),  'Helvetica-Bold'),
            ('FONTSIZE',  (0, 0), (-1, -1), 8),
            ('TEXTCOLOR', (0, 0), (0, -1),  GREY_500),
            ('TEXTCOLOR', (2, 0), (2, -1),  GREY_500),
            ('TEXTCOLOR', (1, 0), (1, -1),  BRAND_DARK),
            ('TEXTCOLOR', (3, 0), (3, -1),  BRAND_DARK),
            ('TOPPADDING',    (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('ROWBACKGROUNDS', (0, 0), (-1, -1), [GREY_100, WHITE]),
        ]))
        story.append(meta_tbl)
        story.append(PageBreak())

    # ------------------------------------------------------------------ tactic summary
    def _tactic_summary(self, story, events, techniques, styles):
        story.append(Paragraph('1.  Executive Summary', styles['section_title']))
        story.append(self._rule())

        tactic_counts: Dict[str, int] = {}
        for e in events:
            t = e.get('mitre_tactic', 'Unknown')
            tactic_counts[t] = tactic_counts.get(t, 0) + 1

        total = len(events)
        body_text = (
            f'This report documents <b>{total} security event{"s" if total != 1 else ""}</b> '
            f'analysed against the MITRE ATT&CK® framework. '
            f'The events span <b>{len(tactic_counts)} tactic{"s" if len(tactic_counts) != 1 else ""}</b> '
            f'and <b>{len(techniques)} unique technique{"s" if len(techniques) != 1 else ""}</b>. '
            f'Events marked <b>CRITICAL</b> require immediate SOC attention.'
        )
        story.append(Paragraph(body_text, styles['body']))
        story.append(Spacer(1, 0.15 * inch))

        # Tactic breakdown table
        rows = [['TACTIC', 'SEVERITY', 'EVENT COUNT', '% OF TOTAL']]
        for tactic in TACTICS_ORDER:
            count = tactic_counts.get(tactic, 0)
            if count == 0:
                continue
            sev = SEVERITY_MAP.get(tactic, 'LOW')
            bg, fg = SEVERITY_COLORS[sev]
            pct = f'{round(count * 100 / max(total, 1))}%'
            rows.append([tactic, sev, str(count), pct])

        col_w = [2.5 * inch, 1.1 * inch, 1.1 * inch, 1.0 * inch]
        tbl = Table(rows, colWidths=col_w, repeatRows=1)
        style_cmds = [
            ('BACKGROUND',    (0, 0), (-1, 0),  BRAND_DARK),
            ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
            ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
            ('FONTSIZE',      (0, 0), (-1, -1), 8),
            ('ALIGN',         (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN',         (1, 0), (-1, -1), 'CENTER'),
            ('TOPPADDING',    (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING',   (0, 0), (-1, -1), 8),
            ('GRID',          (0, 0), (-1, -1), 0.3, GREY_200),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, GREY_100]),
        ]
        # Colour severity column cells
        for i, row in enumerate(rows[1:], 1):
            sev = row[1]
            bg, fg = SEVERITY_COLORS.get(sev, ('#F8FAFC', '#334155'))
            style_cmds += [
                ('BACKGROUND', (1, i), (1, i), colors.HexColor(bg)),
                ('TEXTCOLOR',  (1, i), (1, i), colors.HexColor(fg)),
                ('FONTNAME',   (1, i), (1, i), 'Helvetica-Bold'),
            ]
        tbl.setStyle(TableStyle(style_cmds))
        story.append(tbl)
        story.append(Spacer(1, 0.2 * inch))

    # ------------------------------------------------------------------ kill chain
    def _kill_chain(self, story, events, techniques, styles):
        story.append(Paragraph('2.  MITRE ATT&CK® Kill Chain', styles['section_title']))
        story.append(self._rule())

        present_tactics = [t for t in TACTICS_ORDER if any(
            e.get('mitre_tactic') == t for e in events)]

        # Visual chain strip
        num = len(present_tactics)
        if num:
            box_w = min(1.0 * inch, (7.1 * inch) / num)
            chain_cells = []
            for t in present_tactics:
                bg_hex, fg_hex = TACTIC_COLORS.get(t, ('#E2E8F0', '#334155'))
                short = t.replace(' and ', ' & ').replace('Privilege ', 'Priv. ').replace('Escalation', 'Escal.')
                cell = Paragraph(
                    f'<font color="{fg_hex}"><b>{short}</b></font>',
                    ParagraphStyle('kc', fontSize=6.5, fontName='Helvetica-Bold',
                                   textColor=colors.HexColor(fg_hex), alignment=TA_CENTER, leading=9)
                )
                chain_cells.append(cell)

            chain_tbl = Table([chain_cells], colWidths=[box_w] * num)
            chain_style = [
                ('TOPPADDING',    (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID',          (0, 0), (-1, -1), 0.5, GREY_200),
            ]
            for i, t in enumerate(present_tactics):
                bg_hex, _ = TACTIC_COLORS.get(t, ('#E2E8F0', '#334155'))
                chain_style.append(('BACKGROUND', (i, 0), (i, 0), colors.HexColor(bg_hex)))
            chain_tbl.setStyle(TableStyle(chain_style))
            story.append(chain_tbl)
            story.append(Spacer(1, 0.12 * inch))

        # Techniques list
        if techniques:
            tech_rows = [['TECHNIQUE ID', 'TECHNIQUE NAME', 'TACTIC']]
            for t in techniques:
                tactic = next(
                    (e.get('mitre_tactic', '') for e in events
                     if e.get('mitre_technique_id') == t.get('id')), ''
                )
                tech_rows.append([
                    Paragraph(f'<b>{t.get("id","")}</b>',
                               ParagraphStyle('tc', fontSize=8, fontName='Helvetica-Bold',
                                              textColor=BRAND_ACCENT)),
                    t.get('name', ''),
                    tactic,
                ])
            tech_tbl = Table(tech_rows, colWidths=[1.0 * inch, 3.5 * inch, 2.2 * inch], repeatRows=1)
            tech_tbl.setStyle(TableStyle([
                ('BACKGROUND',    (0, 0), (-1, 0),  BRAND_DARK),
                ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
                ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
                ('FONTSIZE',      (0, 0), (-1, -1), 8),
                ('ALIGN',         (0, 0), (-1, -1), 'LEFT'),
                ('TOPPADDING',    (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING',   (0, 0), (-1, -1), 8),
                ('GRID',          (0, 0), (-1, -1), 0.3, GREY_200),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, GREY_100]),
            ]))
            story.append(tech_tbl)
        story.append(Spacer(1, 0.2 * inch))

    # ------------------------------------------------------------------ event timeline
    def _event_timeline(self, story, events, styles):
        story.append(PageBreak())
        story.append(Paragraph('3.  Detailed Event Timeline', styles['section_title']))
        story.append(self._rule())
        story.append(Paragraph(
            'All events are listed chronologically. Severity is derived from the mapped MITRE tactic. '
            'Confidence reflects keyword-match strength.',
            styles['body']
        ))
        story.append(Spacer(1, 0.1 * inch))

        headers = ['#', 'DATE / TIME', 'TACTIC', 'TECHNIQUE', 'SEV', 'CONF', 'EVENT DESCRIPTION']
        col_w   = [0.25*inch, 0.9*inch, 1.35*inch, 0.65*inch, 0.5*inch, 0.45*inch, 3.15*inch]

        rows = [headers]
        for idx, event in enumerate(events, 1):
            tactic  = event.get('mitre_tactic', 'Unknown')
            tech_id = event.get('mitre_technique_id', '—')
            conf    = event.get('confidence', 0)
            desc    = event.get('description', '')
            ts      = event.get('timestamp', '')[:19].replace('T', '\n')
            sev     = SEVERITY_MAP.get(tactic, 'LOW')

            rows.append([
                str(idx),
                Paragraph(ts, ParagraphStyle('ts', fontSize=7, fontName='Helvetica',
                                             textColor=GREY_700, leading=9)),
                Paragraph(tactic, ParagraphStyle('tac', fontSize=7.5, fontName='Helvetica-Bold',
                                                  textColor=BRAND_DARK, leading=10)),
                Paragraph(f'<b><font color="#3B82F6">{tech_id}</font></b>',
                          ParagraphStyle('tid', fontSize=8, fontName='Helvetica-Bold',
                                         textColor=BRAND_ACCENT)),
                sev,
                f'{conf}%',
                Paragraph(desc, ParagraphStyle('desc', fontSize=7.5, fontName='Helvetica',
                                                textColor=GREY_700, leading=10)),
            ])

        tbl = Table(rows, colWidths=col_w, repeatRows=1)
        style_cmds = [
            ('BACKGROUND',    (0, 0), (-1, 0),  BRAND_DARK),
            ('TEXTCOLOR',     (0, 0), (-1, 0),  WHITE),
            ('FONTNAME',      (0, 0), (-1, 0),  'Helvetica-Bold'),
            ('FONTSIZE',      (0, 0), (-1, 0),  7.5),
            ('ALIGN',         (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN',         (0, 0), (0, -1),  'CENTER'),
            ('ALIGN',         (4, 0), (5, -1),  'CENTER'),
            ('VALIGN',        (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING',    (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING',   (0, 0), (-1, -1), 5),
            ('RIGHTPADDING',  (0, 0), (-1, -1), 5),
            ('GRID',          (0, 0), (-1, -1), 0.3, GREY_200),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, GREY_100]),
            ('FONTSIZE',      (0, 1), (-1, -1), 7.5),
        ]
        # Colour the SEV column
        for i, row in enumerate(rows[1:], 1):
            sev = row[4]
            bg, fg = SEVERITY_COLORS.get(sev, ('#F8FAFC', '#334155'))
            style_cmds += [
                ('BACKGROUND', (4, i), (4, i), colors.HexColor(bg)),
                ('TEXTCOLOR',  (4, i), (4, i), colors.HexColor(fg)),
                ('FONTNAME',   (4, i), (4, i), 'Helvetica-Bold'),
                ('FONTSIZE',   (4, i), (4, i), 7),
            ]
        tbl.setStyle(TableStyle(style_cmds))
        story.append(tbl)
        story.append(Spacer(1, 0.2 * inch))

    # ------------------------------------------------------------------ recommendations
    def _recommendations(self, story, events, styles):
        story.append(PageBreak())
        story.append(Paragraph('4.  SOC Recommendations', styles['section_title']))
        story.append(self._rule())

        tactic_set = set(e.get('mitre_tactic', '') for e in events)
        recs = []

        if 'Credential Access' in tactic_set or 'Privilege Escalation' in tactic_set:
            recs.append(('IMMEDIATE', 'CRITICAL',
                'Reset all credentials on affected systems immediately. '
                'Enforce MFA on all privileged accounts and audit PAM policies.'))
        if 'Exfiltration' in tactic_set or 'Command and Control' in tactic_set:
            recs.append(('IMMEDIATE', 'CRITICAL',
                'Block identified C2 IPs/domains at the perimeter firewall. '
                'Audit outbound DNS, ICMP and unusual port traffic for tunnelling.'))
        if 'Execution' in tactic_set:
            recs.append(('SHORT-TERM', 'HIGH',
                'Investigate all PowerShell and scripting engine activity. '
                'Enable Script Block Logging and AMSI to capture encoded payloads.'))
        if 'Persistence' in tactic_set:
            recs.append(('SHORT-TERM', 'HIGH',
                'Audit scheduled tasks, registry run keys, and startup entries '
                'on all impacted hosts for unauthorised modifications.'))
        if 'Lateral Movement' in tactic_set:
            recs.append(('SHORT-TERM', 'HIGH',
                'Segment impacted network zones. Review RDP, SMB and SSH access '
                'logs. Apply least-privilege to service accounts.'))
        if 'Defense Evasion' in tactic_set:
            recs.append(('SHORT-TERM', 'HIGH',
                'Check for DLL injection, process hollowing, or timestomping artifacts. '
                'Verify integrity of system binaries on affected hosts.'))
        if 'Discovery' in tactic_set:
            recs.append(('MEDIUM-TERM', 'MEDIUM',
                'Review asset exposure — disable unnecessary service banners. '
                'Deploy network deception (honeypots) to detect future recon.'))
        if 'Impact' in tactic_set:
            recs.append(('IMMEDIATE', 'CRITICAL',
                'Isolate affected systems immediately. Verify backup integrity '
                'and initiate recovery procedures per your IR playbook.'))

        # Generic always-present
        recs += [
            ('MEDIUM-TERM', 'MEDIUM',
             'Enrich detected IOCs (IPs, hashes, domains) in your threat intelligence '
             'platform and share with your ISAC if applicable.'),
            ('MEDIUM-TERM', 'MEDIUM',
             'Update SIEM detection rules to include the patterns observed in this '
             'incident. Run retrospective hunt across 90-day log history.'),
            ('LONG-TERM', 'LOW',
             'Conduct a tabletop exercise simulating this attack chain with the '
             'Blue Team. Document lessons learned in the IR runbook.'),
        ]

        for i, (timeframe, sev, text) in enumerate(recs, 1):
            bg, fg = SEVERITY_COLORS.get(sev, ('#F8FAFC', '#334155'))
            rec_row = Table([[
                Table([[
                    [Paragraph(f'<b>{timeframe}</b>',
                                ParagraphStyle('tf', fontSize=6.5, fontName='Helvetica-Bold',
                                               textColor=colors.HexColor(fg), leading=8))],
                    [Paragraph(sev,
                                ParagraphStyle('sv', fontSize=6.5, fontName='Helvetica-Bold',
                                               textColor=colors.HexColor(fg), leading=8))],
                ]], colWidths=[0.9 * inch]),
                Paragraph(f'<b>{i}.</b>  {text}',
                          ParagraphStyle('rt', fontSize=8.5, fontName='Helvetica',
                                         textColor=GREY_700, leading=12)),
            ]], colWidths=[1.0 * inch, 6.0 * inch])
            rec_row.setStyle(TableStyle([
                ('BACKGROUND',    (0, 0), (0, 0), colors.HexColor(bg)),
                ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
                ('ALIGN',         (0, 0), (0, 0),  'CENTER'),
                ('TOPPADDING',    (0, 0), (-1, -1), 7),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
                ('LEFTPADDING',   (0, 0), (-1, -1), 8),
                ('BOX',           (0, 0), (-1, -1), 0.5, GREY_200),
                ('LINEBELOW',     (0, 0), (-1, -1), 0.3, GREY_200),
            ]))
            story.append(KeepTogether([rec_row, Spacer(1, 4)]))

        story.append(Spacer(1, 0.3 * inch))

    # ------------------------------------------------------------------ main
    def generate_pdf(self, incident: Dict[str, Any]) -> bytes:
        pdf_buffer = BytesIO()
        doc = SimpleDocTemplate(
            pdf_buffer,
            pagesize=A4,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.55 * inch,
            bottomMargin=0.45 * inch,
        )
        styles = self._make_styles()
        story  = []

        events     = incident.get('events', [])
        techniques = incident.get('mitre_techniques', [])

        self._cover_page(story, incident, styles)
        self._tactic_summary(story, events, techniques, styles)
        self._kill_chain(story, events, techniques, styles)
        self._event_timeline(story, events, styles)
        self._recommendations(story, events, styles)

        doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
        pdf_buffer.seek(0)
        return pdf_buffer.getvalue()
